### ISSUE TITLE
Backend throws NoManifestFoundException?

### ISSUE THREAD

**Issue by ThomasEg** [automatica-core/automatica#18]
**Describe the bug**
When starting the backend up for the first time the console overflows with a huge amount of NoManifestFoundException similiar to:
```
[15:10:12 DBG] system: Loading file C:\Users\Thomas\Documents\GitHub\Automatica\src\automatica.core\Automatica.Core\bin\Debug\netcoreapp2.2\System.Security.Permissions.dll and check for interfaces
[15:10:12 WRN] system: C:\Users\Thomas\Documents\GitHub\Automatica\src\automatica.core\Automatica.Core\bin\Debug\netcoreapp2.2\System.Security.Permissions.dll does not contain a manifest files
[15:10:12 ERR] system: Could not load Automatica.Core.Rule.RuleFactory...Automatica.Core.Runtime.Core.Plugins.NoManifestFoundException: Exception of type 'Automatica.Core.Runtime.Core.Plugins.NoManifestFoundException' was thrown.
   at Automatica.Core.Runtime.Core.Plugins.Loader.LoadSingle[T](String file, ILogger logger, AutomaticaContext database, Boolean isInDevMode) in C:\Users\Thomas\Documents\GitHub\Automatica\src\automatica.core\Automatica.Core.Runtime\Core\Plugins\Loader.cs:line 194
Automatica.Core.Runtime.Core.Plugins.NoManifestFoundException: Exception of type 'Automatica.Core.Runtime.Core.Plugins.NoManifestFoundException' was thrown.
   at Automatica.Core.Runtime.Core.Plugins.Loader.LoadSingle[T](String file, ILogger logger, AutomaticaContext database, Boolean isInDevMode) in C:\Users\Thomas\Documents\GitHub\Automatica\src\automatica.core\Automatica.Core.Runtime\Core\Plugins\Loader.cs:line 194
```
...about 50ish of these exceptions...the backend does eventuelly start, but i'm having a hard time getting figured things out and i'm wondering if i'm missing stuff because of these errors...

**Expected behavior**
I'd expect the backend to start without any errors...

**automatica.core version**
`develop`-branch on github as of 17-08-2019

**system**
Windows 10, Visual Studio 2019 CE

**Comment by p3root** [comment]
The system searches for drivers and logic plugins in the binaries folders subdirectories drivers/logics. If the folders do not exist it searches in the current working directory. The executeable folder contains a lot of dll's. 

A plugin must be built using the automatica.core azure devops build extensions, the plugin dll will be built with a embedded manifest resource to identify it as a valid automatica.core plugin. If a dll will be loaded that does not include such a ressource the NoManifestFoundException will be thrown. The exception wil be handled.

**Comment by p3root** [comment]
I generate the Drivers and Logics directory if not found. So therefore if you start the system initially no .dll will be tried to load.
