### ISSUE TITLE
Backend throws NullReferenceException when viewing plugins

### ISSUE THREAD

**Issue by ThomasEg** [automatica-core/automatica#19]
**Describe the bug**
On a fresh install a newly started backend, i get this exception:
```
[15:19:34 ERR] microsoft.aspnetcore.server.kestrel: Connection id "0HLP32GMT7SED", Request id "0HLP32GMT7SED:00000001": An unhandled exception was thrown by the application.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Automatica.Core.WebApi.Controllers.PluginsController.GetPlugins() in C:\Users\Thomas\Documents\GitHub\Automatica\src\automatica.core\Automatica.Core.WebApi\Controllers\PluginsController.cs:line 42
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Automatica.Core.WebApi.Exceptions.WebApiErrorMiddleware.Invoke(HttpContext context) in C:\Users\Thomas\Documents\GitHub\Automatica\src\automatica.core\Automatica.Core.WebApi\Exceptions\WebApiErrorMiddleware.cs:line 24
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**To Reproduce**
Fresh/new install, first run...

In the Administration-GUI goto "Plugins"...

**automatica.core version**
`develop`-branch on github

**Comment by p3root** [comment]
Following error of #20 

Should be handled in the FE.

**Comment by p3root** [comment]
Fixed it. I display a error in the FE.
