### ISSUE TITLE
Backend has issues with cloud connection?

### ISSUE THREAD

**Issue by ThomasEg** [automatica-core/automatica#20]
**Describe the bug**
There is two types of exceptions in the backend:
```
[15:10:17 ERR] system: Could not say hi to cloud api
System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Automatica.Core.Internals.Cloud.CloudApi.PostRequest[T](String apiUrl, Object postObject) in C:\Users\Thomas\Documents\GitHub\Automatica\src\automatica.core\Automatica.Core.Internals\Cloud\CloudApi.cs:line 170
   at Automatica.Core.Internals.Cloud.CloudApi.SayHelloToCloud(SayHelloData sayHi) in C:\Users\Thomas\Documents\GitHub\Automatica\src\automatica.core\Automatica.Core.Internals\Cloud\CloudApi.cs:line 89
```
...and....
```
[15:19:33 ERR] system: Could not execute get request to cloud
System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Automatica.Core.Internals.Cloud.CloudApi.GetRequest[T](String apiUrl) in C:\Users\Thomas\Documents\GitHub\Automatica\src\automatica.core\Automatica.Core.Internals\Cloud\CloudApi.cs:line 143
```
I'm not sure if they are related.

**Expected behavior**
I would not expect any exceptions/errors in the log. IF some sort of setup is missing(tokens, keys etc), then i'd except an warning an maybe a reference to how to fix it. Or the frontend telling me to fix it on first login...

**Comment by p3root** [comment]
At the moment the Cloud validates every connection to the API. Your connection is not valid. Therefore the BE has problems with the cloud connection.

You can send me your server id (root node in the configuration section -> propertyeditor  -> Server UID) and I'll give you an API key to access the cloud api if you want.

This exception will be handled but should be displayed in the FE!
